---
title: "Frequently Asked Questions"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Are children allowed at the wedding?

No, unfortunately we cannot accommodate children at the wedding. Only named invitees please!

## What is the dress code?

We do not have a specific dress code and want you to dress in a way that you feel comfortable. Bridal party will be wearing black, but this should not limit you from wearing that color - just please refrain from wearing any black dresses from Park and Fifth.  

## What do I do between the ceremony and cocktail hour?

The short answer is, whatever you like! There is time to go back to your hotel, walk through the public gardens, or pop up the street to the Oxford Tap Room for a quick beer before the reception gets started. 

St. Mary's Boat Club is down the hill from the church and is a lovely area to walk. It holds many of the beautiful old Halifax homes along the Northwest Arm. If you're a little early to the boat club, that is sans qualms! The deck overlooks the arm and is a lovely place to enjoy beautiful views and breathe in that fresh ocean air. 

## What are the available accommodations?

There will be more information to come for this. We have listed 3 hotels that we have reached out to for rates, which will be available to us in the new year. Stay tuned! 
