---
title: "Alex & Chris"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
```

# Favourite Places & Important Locations

Map of our favourite places.

```{r map, include=TRUE, results=TRUE}
df <- read.csv("fav_places.csv")

logos <- awesomeIconList(
  "bar" = makeAwesomeIcon(
    icon = "beer-mug-empty",
    markerColor = "blue",
    library = "fa"
  ),
  "restaurant" = makeAwesomeIcon(
    icon = "utensils",
    markerColor = "blue",
    library = "fa"
  ),
  "church" = makeAwesomeIcon(
    icon = "church",
    markerColor = "red",
    library = "fa"
  ),
  "reception" = makeAwesomeIcon(
    icon = "heart",
    markerColor = "red",
    library = "fa"
  ),
  "home" = makeAwesomeIcon(
    icon = "house",
    markerColor = "green",
    library = "fa"
  ),
  "coffee" = makeAwesomeIcon(
    icon = "mug-saucer",
    markerColor = "orange",
    library = "fa"
  )
)

m <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lat = 44.65065108508493, lng = -63.593375588138834, zoom = 13) %>%
  addAwesomeMarkers(
    data = df,
    lat = ~lat, lng = ~lng,
    icon = logos[df$Type],
    popup = paste0(
      df$Name, "<br/>", df$Address, "<br/>Description: ", df$Description
    )
  )
m
```
