---
title: "Wedding Update"
description: |
  RSVP reminder, accomodations, schedule, and more
site: distill::distill_website
---

Hi everyone - we just wanted to send a reminder/update email. In here you'll find:

- A note about invites
- A reminder to RSVP if you have not already
- Information on accomodations
- A more firm schedule of the day/weekend
- Info on meal selection

## Invites and RSVP Reminders

A note about our invites - we mailed them around the time of the postal strike and should have been a bit more vigilant about whether people received them or not. If you're getting this email, you are invited. We are missing some emails too, particularly of some spouses. Significant others in general were invited but if you have any uncertainty please feel free to reach out to us directly. 

And on that note, if you haven't RSVPed yet please do! It is very helpful to us to have this information as early as possible. You can RSVP [here](rsvp.html).

## Accommodations

We have a block of rooms at the Cambridge Suites FOR $219/night which you can book at this link: [https://reservations.travelclick.com/13605?groupID=4655544](https://reservations.travelclick.com/13605?groupID=4655544).

## Schedule

### Friday, September 26, 2025

- Start time still TBD: Stillwell Freehouse - all welcome! We have booked out the Freehouse for a private event. Please join us at our favourite local establishment. 

### Saturday, September 27, 2025

- 2pm: Ceremony @ St. Thomas Aquinas Catholic Church - please try to be seated by 2pm! Expect about an hour. 
- 3pm-4:30pm: this time is yours, check the map of our fav places on the home page of the website for lots of good suggestions, or just pop back home or to your hotel
- 4:30pm: Cocktail hour - bevs and snacks on the deck of St. Mary's Boat Club if weather cooperates inside otherwise :)
- 6pm: Move inside the boat club for dinner, speeches, dancing, etc. 

## Meal selection

We will start sending out meal selecion to those that have RSVPed "Yes" in the coming weeks. We thank you for a quick reply!! :)